use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::{
    path::{Path, PathBuf},
    process::Command,
    sync::{Arc, Mutex},
};
use sysinfo::{Disks, Networks, System};
use walkdir::WalkDir;
use tauri::{AppHandle, Emitter, State};

// ============================================================================
// DATA STRUCTURES
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CacheLocation {
    pub id: String,
    pub path: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub hint: String,
    pub impact: String,
    pub risk: String,
    pub size: u64,
    pub size_human: String,
    pub selected: bool,
    pub exists: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemStats {
    pub cpu_percent: f32,
    pub cpu_count: usize,
    pub memory: MemoryStats,
    pub disk: DiskStats,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryStats {
    pub total: u64,
    pub used: u64,
    pub free: u64,
    pub percent: f32,
    pub total_human: String,
    pub used_human: String,
    pub free_human: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiskStats {
    pub total: u64,
    pub used: u64,
    pub free: u64,
    pub percent: f32,
    pub total_human: String,
    pub used_human: String,
    pub free_human: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanProgress {
    pub current: usize,
    pub total: usize,
    pub percent: u8,
    pub current_location: String,
    pub found_count: usize,
    pub total_size: u64,
}

// ============================================================================
// STATE
// ============================================================================

pub struct CleanerState {
    pub scan_results: Mutex<Vec<CacheLocation>>,
    pub scan_in_progress: Mutex<bool>,
    pub system: Mutex<System>,
    pub disks: Mutex<Disks>,
}

impl CleanerState {
    pub fn new() -> Self {
        Self {
            scan_results: Mutex::new(Vec::new()),
            scan_in_progress: Mutex::new(false),
            system: Mutex::new(System::new_all()),
            disks: Mutex::new(Disks::new_with_refreshed_list()),
        }
    }
}

// ============================================================================
// LOGIC
// ============================================================================

pub fn human_readable_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB", "TB", "PB"];
    let mut size = bytes as f64;
    let mut unit_index = 0;

    while size >= 1024.0 && unit_index < UNITS.len() - 1 {
        size /= 1024.0;
        unit_index += 1;
    }

    if unit_index == 0 {
        format!("{} {}", bytes, UNITS[0])
    } else {
        format!("{:.1} {}", size, UNITS[unit_index])
    }
}

pub fn get_directory_size(path: &Path) -> u64 {
    WalkDir::new(path)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter_map(|e| e.metadata().ok())
        .filter(|m| m.is_file())
        .map(|m| m.len())
        .sum()
}

pub fn get_cache_locations() -> Vec<CacheLocation> {
    let os = std::env::consts::OS;
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("/"));
    let mut locations = Vec::new();

    if os == "macos" {
        locations.push(CacheLocation {
            id: "user_caches".into(),
            path: home.join("Library/Caches").to_string_lossy().to_string(),
            name: "User Caches".into(),
            description: "Application caches for the current user".into(),
            category: "System".into(),
            hint: "Speeds up loading times.".into(),
            impact: "Apps will regenerate cache.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
        locations.push(CacheLocation {
            id: "system_logs".into(),
            path: home.join("Library/Logs").to_string_lossy().to_string(),
            name: "User Logs".into(),
            description: "Log files generated by applications".into(),
            category: "System".into(),
            hint: "Used for debugging.".into(),
            impact: "Safe to delete.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
    } else if os == "windows" {
        locations.push(CacheLocation {
            id: "temp_files".into(),
            path: std::env::var("TEMP").unwrap_or_else(|_| String::from("C:\\Windows\\Temp")),
            name: "Temporary Files".into(),
            description: "Windows Temp folder".into(),
            category: "System".into(),
            hint: "Temporary files created by apps.".into(),
            impact: "Safe to delete.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
        if let Some(local_appdata) = dirs::data_local_dir() {
            locations.push(CacheLocation {
                id: "local_temp".into(),
                path: local_appdata.join("Temp").to_string_lossy().to_string(),
                name: "User Temp".into(),
                description: "User localized temporary files".into(),
                category: "System".into(),
                hint: "Safe to clean.".into(),
                impact: "Safe to delete.".into(),
                risk: "low".into(),
                size: 0,
                size_human: "0B".into(),
                selected: true,
                exists: false,
            });
        }
    } else {
        // linux
        if let Some(cache_dir) = dirs::cache_dir() {
            locations.push(CacheLocation {
                id: "user_caches".into(),
                path: cache_dir.to_string_lossy().to_string(),
                name: "User Caches".into(),
                description: "User cache directory (~/.cache)".into(),
                category: "System".into(),
                hint: "Speeds up loading times.".into(),
                impact: "Apps will regenerate cache.".into(),
                risk: "low".into(),
                size: 0,
                size_human: "0B".into(),
                selected: true,
                exists: false,
            });
        }
    }

    locations
}

// ============================================================================
// TAURI COMMANDS
// ============================================================================

#[tauri::command]
pub async fn start_scan(app: AppHandle, state: State<'_, CleanerState>) -> Result<(), String> {
    let mut in_progress = state.scan_in_progress.lock().unwrap();
    if *in_progress {
        return Ok(());
    }
    *in_progress = true;
    drop(in_progress);

    let mut locations = get_cache_locations();
    let total = locations.len();
    let mut found_count = 0;
    let mut total_size = 0;

    for (i, loc) in locations.iter_mut().enumerate() {
        let _ = app.emit("scan-progress", ScanProgress {
            current: i,
            total,
            percent: ((i as f32 / total as f32) * 100.0) as u8,
            current_location: loc.path.clone(),
            found_count,
            total_size,
        });

        let path = PathBuf::from(&loc.path);
        loc.exists = path.exists();
        if loc.exists {
            let size = get_directory_size(&path);
            loc.size = size;
            loc.size_human = human_readable_size(size);
            if size > 0 {
                found_count += 1;
                total_size += size;
            }
        }
        
        // Simulating artificial delay for cool scanning effect
        std::thread::sleep(std::time::Duration::from_millis(150));
    }

    // Finalize
    let mut scan_results = state.scan_results.lock().unwrap();
    *scan_results = locations.clone();
    
    let mut in_progress = state.scan_in_progress.lock().unwrap();
    *in_progress = false;

    let _ = app.emit("scan-progress", ScanProgress {
        current: total,
        total,
        percent: 100,
        current_location: "Scan complete".into(),
        found_count,
        total_size,
    });

    Ok(())
}

#[tauri::command]
pub fn get_scan_results(state: State<'_, CleanerState>) -> Vec<CacheLocation> {
    state.scan_results.lock().unwrap().clone()
}

#[tauri::command]
pub async fn clean_items(items: Vec<String>, state: State<'_, CleanerState>) -> Result<u64, String> {
    let results = state.scan_results.lock().unwrap().clone();
    let mut freed_space = 0;

    for id in items {
        if let Some(loc) = results.iter().find(|l| l.id == id) {
            let path = PathBuf::from(&loc.path);
            if path.exists() {
                if let Ok(_) = std::fs::remove_dir_all(&path) {
                    freed_space += loc.size;
                    // Recreate empty dir
                    let _ = std::fs::create_dir_all(&path);
                }
            }
        }
    }

    Ok(freed_space)
}

#[tauri::command]
pub fn get_system_stats(state: State<'_, CleanerState>) -> SystemStats {
    let mut sys = state.system.lock().unwrap();
    let mut disks = state.disks.lock().unwrap();
    
    sys.refresh_cpu_usage();
    sys.refresh_memory();
    disks.refresh_list();

    let total_mem = sys.total_memory();
    let used_mem = sys.used_memory();
    let free_mem = total_mem - used_mem;

    let dt = total_mem as f32;
    let du = used_mem as f32;
    let mem_percent = if dt > 0.0 { (du / dt) * 100.0 } else { 0.0 };

    let mut disk_total = 0;
    let mut disk_used = 0;
    
    for disk in disks.list() {
        disk_total += disk.total_space();
        let avail = disk.available_space();
        disk_used += disk.total_space().saturating_sub(avail);
    }

    let disk_free = disk_total - disk_used;
    let disk_percent = if disk_total > 0 {
        ((disk_used as f64 / disk_total as f64) * 100.0) as f32
    } else {
        0.0
    };

    SystemStats {
        cpu_percent: sys.global_cpu_usage(),
        cpu_count: sys.cpus().len(),
        memory: MemoryStats {
            total: total_mem,
            used: used_mem,
            free: free_mem,
            percent: mem_percent,
            total_human: human_readable_size(total_mem),
            used_human: human_readable_size(used_mem),
            free_human: human_readable_size(free_mem),
        },
        disk: DiskStats {
            total: disk_total,
            used: disk_used,
            free: disk_free,
            percent: disk_percent,
            total_human: human_readable_size(disk_total),
            used_human: human_readable_size(disk_used),
            free_human: human_readable_size(disk_free),
        }
    }
}
