use std::path::PathBuf;
use super::models::CacheLocation;

pub fn get_cache_locations() -> Vec<CacheLocation> {
    let os = std::env::consts::OS;
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("/"));
    let mut locations = Vec::new();

    if os == "macos" {
        locations.push(CacheLocation {
            id: "user_caches".into(),
            path: home.join("Library/Caches").to_string_lossy().to_string(),
            name: "User Caches".into(),
            description: "Application caches for the current user".into(),
            category: "System".into(),
            hint: "Speeds up loading times.".into(),
            impact: "Apps will regenerate cache.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
        locations.push(CacheLocation {
            id: "system_logs".into(),
            path: home.join("Library/Logs").to_string_lossy().to_string(),
            name: "User Logs".into(),
            description: "Log files generated by applications".into(),
            category: "System".into(),
            hint: "Used for debugging.".into(),
            impact: "Safe to delete.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
    } else if os == "windows" {
        locations.push(CacheLocation {
            id: "temp_files".into(),
            path: std::env::temp_dir().to_string_lossy().to_string(),
            name: "Temporary Files".into(),
            description: "System Temp folder".into(),
            category: "System".into(),
            hint: "Temporary files created by apps.".into(),
            impact: "Safe to delete.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
        if let Some(local_appdata) = dirs::data_local_dir() {
            locations.push(CacheLocation {
                id: "local_temp".into(),
                path: local_appdata.join("Temp").to_string_lossy().to_string(),
                name: "User Temp".into(),
                description: "User localized temporary files".into(),
                category: "System".into(),
                hint: "Safe to clean.".into(),
                impact: "Safe to delete.".into(),
                risk: "low".into(),
                size: 0,
                size_human: "0B".into(),
                selected: true,
                exists: false,
            });
        }
    } else if let Some(cache_dir) = dirs::cache_dir() {
        locations.push(CacheLocation {
            id: "user_caches".into(),
            path: cache_dir.to_string_lossy().to_string(),
            name: "User Caches".into(),
            description: "User cache directory (~/.cache)".into(),
            category: "System".into(),
            hint: "Speeds up loading times.".into(),
            impact: "Apps will regenerate cache.".into(),
            risk: "low".into(),
            size: 0,
            size_human: "0B".into(),
            selected: true,
            exists: false,
        });
    }

    locations
}
